export const copy = {
  heroTitle: '青楓館式 英語開発',
  heroSubtitle: '日常会話に特化した発音練習',
  getStarted: 'はじめる',
  stageCleared: (n: number) => `ステージ${n}をクリア！`,
  noHearts: 'ハートがなくなりました',
  tryTomorrow: 'また明日チャレンジ',
  missionTitle: '🎯 今日のミッション',
  missionSubtitle: '英語力をレベルアップしよう',
  stageLocked: 'ロック中',
  stageActive: '挑戦する',
  stageCompleted: '完了',
  nextStage: '次のステージ',
  backToHome: 'ホームに戻る',
  practiceAgain: 'もう一度練習',
  greatJob: '素晴らしい！',
  keepGoing: '続けよう！',
  almostThere: 'あと少し！',
  needMorePractice: 'もう少し練習が必要です',
  perfectPronunciation: '完璧な発音です！',
  goodPronunciation: '良い発音です',
  needsImprovement: '改善の余地があります',
  pronunciationHint: '発音のコツ',
  listenAndRepeat: '聞いて、真似して',
  speakClearly: 'はっきりと話そう',
  takeYourTime: '焦らずに',
  youCanDoIt: 'できる！',
  excellent: '優秀',
  good: '良好',
  fair: '普通',
  needsWork: '要改善',
  needsHelp: '大幅改善必要'
} 